### ISSUE TITLE
Merge webapps folder in multimodule project

### ISSUE THREAD

**Issue by odwrotnie** [earldouglas/xsbt-web-plugin#292] opened 2015-12-01 21:30 UTC
How do you do [this](https://github.com/earldouglas/xsbt-web-plugin/issues/67) in version 2.1.0?

**Comment by earldouglas** [comment] 2015-12-01 22:15
@odwrotnie: For now, you can't.  Please see https://github.com/earldouglas/xsbt-web-plugin/issues/228 for more discussion.

**Comment by earldouglas** [comment] 2015-12-01 22:15
Closing as duplicate of https://github.com/earldouglas/xsbt-web-plugin/issues/228

**Closed by earldouglas** 2015-12-01 22:15 UTC

**Comment by odwrotnie** [comment] 2015-12-01 22:19
Is there any workaround?

**Comment by earldouglas** [comment] 2015-12-01 22:27
There are two ways that could work:

1. Use [`webappPostProcess`][1] to copy all of your webapp resources into the target webapp directory
1. Use a custom [`sourceDirectory`][2], and copy all of your webapp resources into it *before* packaging the webapp itself

[1]: https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.1.md#massaging-the-war-file
[2]: https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.1.md#web-application-resources

**Comment by earldouglas** [comment] 2015-12-01 22:29
Sorry for the regression.  If this is a feature you'd like to see again in 2.x, please voice your support in #228.

**Comment by odwrotnie** [comment] 2015-12-02 08:10
Are you able to tell me how can I use webappPostProcess? I have no idea.

**Comment by earldouglas** [comment] 2015-12-02 15:49
What's the structure of your project?  Is it a single sbt module with *webapp* content spread around multiple directoires?  Is it a multi-module project?

Here's a simple way to do it, using sbt's [`IO#copyDirectory`][1]:

```scala
webappPostProcess := {
  webappDir: File =>
    val baseDir = baseDirectory.value / "src" / "main"
    IO.copyDirectory(baseDir / "webapp1", webappDir)
    IO.copyDirectory(baseDir / "webapp2", webappDir)
    IO.copyDirectory(baseDir / "webapp3", webappDir)
}
```

Basically this says:

> After compiling the project and prepping everything in *target/webapp*, copy the contents of *src/main/webapp1* (and *webappp2*, and *webapp3*) into *target/webapp*.

[1]: http://www.scala-sbt.org/0.13.7/api/index.html#sbt.IO$

**Comment by nafg** [comment] 2016-01-29 04:21
I think this should be a separate ticket from #228, that's about custom folders (a shorthand for the code snippet above), while ideally it should either be default behavior or opt in on the subproject level, i.e., I should be able to specify subprojects A, B, and C, and it will use all of their src/main/webapp folders.

**Comment by earldouglas** [comment] 2016-01-29 05:03
@nafg: That's an interesting point.  Can you go into more detail?  In your use case, are A, B, and C all Web projects that each enable one of the container plugins?  Do they each have a *web.xml* file?

**Comment by nafg** [comment] 2016-01-31 01:48
Two use cases:
1. Subprojects views-volunteers and views-requests contain Lift snippets
and templates (in src/main/webapp), and subproject app depends
(transitively) on both, and has the cake pattern end of the world including
the Lift Boot implementation, and enables the Jetty autoplugin
2. App doesn't have the final end-of-the-world or the plugin; instead, it
ties up most loose ends, but there's still app-clientA and app-clientA,
containing per-customer customizations. So enablePlugins(JettyPlugin) will
have to be applied to both, but whatever common ground could be pushed up
to app, such as web.xml, should be.
